### PR TITLE
Fix reservoir range showing outside the map

### LINKED ISSUE #430: Reservoir range gives artifacts when hovering near map edge
This only seems to happen on enormous maps at the north and south edges.
reservoir-map-edge

@crudelios is going to pick this up.

### PR DESCRIPTION
**Pull request by crudelios**
Fixes #430

### CODE REVIEW

File: src/city/view.c [hunk 1]
```diff
@@ -581,17 +592,17 @@ void city_view_foreach_tile_in_range(int grid_offset, int size, int radius, map_
...
-            do_valid_callback(x + x_delta * tile, y - y_offset + y_delta * tile, offset_north + tile, callback);
-            do_valid_callback(x - x_delta * tile, y - y_offset + y_delta * tile, offset_north + tile * GRID_SIZE, callback);
-            do_valid_callback(x + x_delta * tile, y + y_offset - y_delta * tile, offset_south - tile * GRID_SIZE, callback);
-            do_valid_callback(x - x_delta * tile, y + y_offset - y_delta * tile, offset_south - tile, callback);
+            do_valid_callback(x + x_delta * tile, y - y_offset + y_delta * tile, move_grid_offset_by_delta(grid_offset, tile + offset_north, offset_north), callback);
+            do_valid_callback(x - x_delta * tile, y - y_offset + y_delta * tile, move_grid_offset_by_delta(grid_offset, offset_north, tile + offset_north), callback);
+            do_valid_callback(x + x_delta * tile, y + y_offset - y_delta * tile, move_grid_offset_by_delta(grid_offset, offset_south, offset_south - tile), callback);
+            do_valid_callback(x - x_delta * tile, y + y_offset - y_delta * tile, move_grid_offset_by_delta(grid_offset, offset_south - tile, offset_south), callback);
```
Comment (bvschaik) [inline src/city/view.c:605]: Please break up the lines so they're not too long: breaking just before the `move_...` function calls should be good.

File: src/city/view.c [hunk 2]
```diff
@@ -553,6 +553,17 @@ void city_view_foreach_valid_map_tile(map_callback *callback1, map_callback *cal
...
+    if (grid_x + x < 0 || grid_x + x >= GRID_SIZE ||
+        grid_y + y < 0 || grid_y + y >= GRID_SIZE) {
+        return 0;
+    }
+    return grid_offset + map_grid_delta(x, y);
+}
+
 static void do_valid_callback(int x, int y, int grid_offset, map_callback *callback)
 {
     if (map_image_at(grid_offset) >= 6) {
```
Comment (bvschaik) [inline src/city/view.c:569]: Shouldn't we check for `grid_offset != 0` as well?

Comment (crudelios) [reply src/city/view.c:569]: In the current usage it makes no difference, as `grid_offset` is guaranteed to be valid.

Comment (bvschaik) [reply src/city/view.c:569]: I know, but it saves a call to `map_image_at` and is future-proof, in case we start to return for example `-1` for invalid offsets.
