### PR TITLE
Fix screen not showing on Windows after pressing ctrl+alt+del

### LINKED ISSUE #528: Game goes black when I go to task manager
When I hit ctrl alt delete on Windows 10 while playing Julius, then try going back into the game, the game display goes completely black. I can still hear audio, but I cannot see what is happening in-game. Any recommendations?

### PR DESCRIPTION
**Pull request by crudelios**
Fixes #528

### CODE REVIEW

File: src/platform/screen.c [hunk 1]
```diff
@@ -289,6 +289,23 @@ void platform_screen_center_window(void)
...
+#ifdef _WIN32
+void platform_screen_recreate_texture(void)
+{
+    // On Windows, if ctrl + alt + del is pressed during fullscreen, the rendering context may be lost for a few frames
+    // after restoring the window, preventing the texture from being recreated. This forces an attempt to recreate the
+    // texture every frame to bypass that issue.
+    if (!SDL.texture && SDL.renderer && setting_fullscreen()) {
+        SDL_DisplayMode mode;
+        SDL_GetWindowDisplayMode(SDL.window, &mode);
+        system_resize(scale_pixels_to_logical(mode.w), scale_pixels_to_logical(mode.h));
```
Comment (bvschaik) [inline src/platform/screen.c:301]: `system_resize` causes an SDL resize event which is handled in the next run of the event loop. Do we really need that, or is `screen_set_resolution` sufficient?

Comment (crudelios) [reply src/platform/screen.c:301]: We need at least a `platfofm_screen_resize` to recreate the texture.
