### PR TITLE
Fix loading empty files

### LINKED ISSUE #234: Folders ending with ".sav" get listed as files and can be opened
If you save a folder as `<any name>.sav`, then that folder will be listed as a valid city in the Load/Save/Delete dialog.

If you then try to open the file, this will happen:

empty_city

As you can see, the game loads an empty city with no terrain and everything set to `0`. The `emperor wrath` message appears because your empire rating is also `0`.

In C3, while the folder appears as a city in the Load/Save/Delete dialog, if you try to open it it will refuse saying that the file does not exist.

Suggestions to fix the bug:
* Do not show folders ending with `.sav` as cities in the Load/Save/Delete dialog. This can easily be done by adding a check for  `entry->d_type == DT_REG` in the function `dir_find_files_with_extension` of file `src/core/dir.c`, which should only check for files anyway.
* This, however, does not prevent the user from manually typing the folder name, thus loading an empty file. To fix that, we should check the return value of the `game_file_load_saved_game` (and friends) in function `button_ok_cancel` of file `src/window/file_dialog.c`, triggering a `File does not exist` message if the function returns `0`.

### PR DESCRIPTION
**Pull request by crudelios**
Fix #234

### CODE REVIEW

File: src/core/dir.c [hunk 1]
```diff
@@ -77,8 +86,15 @@ const dir_listing *dir_find_files_with_extension(const char *extension)
         return &listing;
     }
     fs_dir_entry *entry;
+    struct stat file_info;
     while ((entry = fs_dir_read(d)) && listing.num_files < DIR_MAX_FILES) {
         const char *name = dir_entry_name(entry);
+        if (stat(name, &file_info) != -1) {
```
Comment (bvschaik) [inline src/core/dir.c]: We do not need stat for this, the entry contains a d_type variable. Or is that not good enough?

File: src/core/dir.c [hunk 2]
```diff
@@ -77,8 +86,15 @@ const dir_listing *dir_find_files_with_extension(const char *extension)
...
+            int m = file_info.st_mode;
+            if (S_ISDIR(m) || S_ISCHR(m) || S_ISBLK(m) || S_ISFIFO(m) || S_ISLNK(m) || S_ISSOCK(m)) {
```
Comment (bvschaik) [inline src/core/dir.c]: Allow symlinks please.

File: src/game/file_io.c [hunk 3]
```diff
@@ -633,14 +635,18 @@ int game_file_io_read_saved_game(const char *filename, int offset)
     log_info("Loading saved game", filename, 0);
     FILE *fp = file_open(dir_get_case_corrected_file(filename), "rb");
     if (!fp) {
+        log_error("Unable to load game", 0, 0);
```
Comment (bvschaik) [inline src/game/file_io.c]: Add filename as 2nd param so it is included in the log message.

File: src/game/file_io.c [hunk 4]
```diff
@@ -633,14 +635,18 @@ int game_file_io_read_saved_game(const char *filename, int offset)
...
     }
     if (offset) {
         fseek(fp, offset, SEEK_SET);
     }
-    savegame_read_from_file(fp);
+    int result = savegame_read_from_file(fp);
     file_close(fp);
-
+    if (!result) {
+        log_error("Unable to load game", 0, 0);
```
Comment (bvschaik) [inline src/game/file_io.c]: Same as above

**Comment by bvschaik** [comment]
Did you test all campaign saved games from mission1.pak? Those were made using a pre-release version of C3 so they may miss some fields.

File: src/game/file_io.c (hunk 3 above)
Comment (crudelios) [reply src/game/file_io.c]: I didn't do that because the log will already be:

```
Loading save game: <save game>
ERROR: Unable to load game
```

Writing the file name twice feels redundant...

File: src/core/dir.c (hunk 1 above)
Comment (crudelios) [reply src/core/dir.c]: MinGW for windows does not have `d_type`, so I had to resort to `stat`

**Comment by crudelios** [comment]
>Did you test all campaign saved games from mission1.pak?

No I did not! I also don't have them available. Do you have them? If so please send them so I can test.

**Comment by bvschaik** [comment]
They are contained in `mission1.pak` which ismpart of the C3 installation. You can test them by cheating your way through the campaign.

**Comment by crudelios** [comment]
I'm no cheat! I'll do them all fair and square! Give me a month, I'll report back 😆

**Comment by bvschaik** [comment]
Haha, a month is a bit optimistic I guess 😉

**Comment by crudelios** [comment]
Because I'm such a good player, I already legitimately played through both the peaceful and military missions (as well as all the base CCK cities) and can happily report that everything works.

**Comment by bvschaik** [comment]
To be honest... I played through the economic campaign on very easy when I was just learning, I later played through the military one on normal, I believe. I never went back to do them all on hard. I should perhaps do that one day using Julius 😂

**Comment by crudelios** [comment]
Challenge: try getting more than 200 people on very hard :P
